site_name: DVNZ Docs
theme:
  name: material
  logo: assets/logo.png
  palette:
    scheme: slate
  features:
    - navigation.tabs
    - navigation.indexes


copyright: Copyright &copy; 2025 Digital Voice New Zealand.  Released under <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blan">CC BY-NC-SA</a>

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/digitalvoicenz/wiki
    - icon: fontawesome/brands/discord
      link: https://discord.gg/87hz8GYa

extra_css:
  - assets/extra.css

nav:
  - Home: 
    - Welcome: index.md
    - Connect: connect.md
    - Channels: channels.md
    - Contributing: resources/contributing.md
  - NZSIP: 
    - About: nzsip/index.md
    - User Guide: nzsip/users.md
    - Device Support: 
      - Index: nzsip/devices/index.md
      - AllStarLink: nzsip/devices/allstar.md
      - Asterisk: nzsip/devices/asterisk.md
      - Cisco 79xx: nzsip/devices/cisco79xx.md
      - Linphone: nzsip/devices/linphone.md
      - Yealink SIP T2: nzsip/devices/yealink-sipt2.md
    - FAQ: nzsip/faq.md
  - DMR:
    - Digital Voice:
      - About: dvdmr/index.md
      - Setup Guide: dvdmr/guides/index.md
    - FreeDMR: freedmr/index.md
  - XLX299:
    - About: xlx/index.md
  - Resources: 
    - Index: resources/index.md
    - Software: resources/downloads.md
    - Concepts:
      - Reflectors: resources/reflectors.md
      - VoIP Introduction: resources/voip.md
    - Guides:
      - Pi-Star: resources/guides/pistar.md
    - Contributing: resources/contributing.md





markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - footnotes


plugins:
  - search
  - blog
  - tags




