site_name: DVNZ Docs
theme:
  name: material
  logo: assets/logo.png
  palette:
    scheme: slate
  features:
    - navigation.tabs
    - navigation.indexes

extra_css:
  - assets/extra.css

nav:
  - Home: 
    - Welcome: index.md
    - Connect: connect.md
    - Channels: channels.md
  - NZSIP: 
    - About: nzsip/index.md
    - User Guide: nzsip/users.md
    - Device Support: 
      - Index: nzsip/devices/index.md
      - Asterisk: nzsip/devices/asterisk.md
      - Cisco 79xx: nzsip/devices/cisco79xx.md
      - Linphone: nzsip/devices/linphone.md
  - DMR:
    - Digital Voice:
      - About: dvdmr/index.md
      - Setup Guide: dvdmr/guides/index.md
    - FreeDMR: freedmr/index.md
  - XLX299:
    - About: xlx/index.md
  - Resources: 
    - Index: resources/index.md
    - Software: resources/downloads.md
    - Concepts:
      - Reflectors: resources/reflectors.md
      - VoIP Introduction: resources/voip.md
    - Guides:
      - Pi-Star: resources/guides/pistar.md
    - Contributing: resources/contributing.md





markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - blog
  - tags



